@echo off
:: ============================================================
:: WeaR Lang v1.0 Bootstrap Build Script
:: ============================================================
:: This script performs the official self-hosting bootstrap to
:: create the production WeaR Lang compiler from source.
::
:: Requirements:
::   - wearc.exe (Bootstrap Compiler)
::   - compiler.wr (WeaR Compiler Source)
::   - runtime.c (C Runtime Library)
::   - GCC in PATH (MinGW recommended)
:: ============================================================

setlocal enabledelayedexpansion

echo.
echo ============================================================
echo   WeaR Lang v1.0 - Bootstrapping Ritual
echo ============================================================
echo.

:: Check prerequisites
echo [PREREQUISITE CHECK]
echo.

set BOOTSTRAP_COMPILER=NONE

if exist "wearc.exe" (
    set BOOTSTRAP_COMPILER=wearc.exe
    echo   [OK] wearc.exe found (Stage-0 Bootstrap)
)

if "%BOOTSTRAP_COMPILER%"=="NONE" (
    if exist "wear.exe" (
        set BOOTSTRAP_COMPILER=wear.exe
        echo   [OK] wear.exe found (Self-Hosted Bootstrap)
    )
)

if "%BOOTSTRAP_COMPILER%"=="NONE" (
    echo ERROR: No compiler found!
    echo Need either 'wearc.exe' [Stage-0] or 'wear.exe' [Previous Version]
    exit /b 1
)

if not exist "compiler.wr" (
    echo ERROR: compiler.wr not found!
    echo The WeaR compiler source is missing.
    exit /b 1
)
echo   [OK] compiler.wr found

if not exist "runtime.c" (
    echo ERROR: runtime.c not found!
    echo The C runtime library is missing.
    exit /b 1
)
echo   [OK] runtime.c found

where gcc >nul 2>&1
if errorlevel 1 (
    echo ERROR: GCC not found in PATH!
    echo Please install MinGW and add it to PATH.
    exit /b 1
)
echo   [OK] GCC found

echo.
echo ============================================================
echo   STEP 1: The Birth (Generation 1)
echo ============================================================
echo   Using bootstrap (%BOOTSTRAP_COMPILER%) to compile compiler.wr...
echo.

:: Step 1: Bootstrap compiles compiler.wr
copy /y compiler.wr input.wr >nul 2>&1
%BOOTSTRAP_COMPILER%
:: wear.exe / wearc.exe produce output.c by default.
:: We rename it to stage1.c
if exist "output.c" (
    move /y output.c stage1.c >nul 2>&1
) else (
    if exist "stage1.c" (
        echo   [NOTE] Using existing stage1.c [bootstrap might have outputted defined name?]
    ) else (
        echo ERROR: Bootstrap compilation failed! No output.c generated.
        exit /b 1
    )
)

echo   [OK] stage1.c generated
echo   Compiling stage1.c with GCC...

gcc -O2 -o compiler_gen1.exe stage1.c

if errorlevel 1 (
    echo ERROR: GCC compilation of stage1.c failed!
    exit /b 1
)

if not exist "compiler_gen1.exe" (
    echo ERROR: compiler_gen1.exe was not created!
    exit /b 1
)

echo   [OK] compiler_gen1.exe created (Generation 1 Compiler)

echo.
echo ============================================================
echo   STEP 2: The Proof (Generation 2 - Self-Hosting)
echo ============================================================
echo   Using Generation 1 compiler to compile itself...
echo.

:: Step 2: Gen1 compiles compiler.wr (self-hosting!)
copy /y compiler.wr input.wr >nul 2>&1
compiler_gen1.exe

if errorlevel 1 (
    echo ERROR: Generation 1 self-compilation failed!
    exit /b 1
)

:: Rename output.c to stage2.c
if exist "output.c" (
    move /y output.c stage2.c >nul 2>&1
) else (
    echo ERROR: output.c was not generated by Gen1 compiler!
    exit /b 1
)

echo   [OK] stage2.c generated (Self-Hosted Output)
echo   Compiling stage2.c with GCC...

gcc -O2 -o wear.exe stage2.c

if errorlevel 1 (
    echo ERROR: GCC compilation of stage2.c failed!
    exit /b 1
)

if not exist "wear.exe" (
    echo ERROR: wear.exe was not created!
    exit /b 1
)

echo   [OK] wear.exe created (WeaR Lang v1.0 Compiler)

echo.
echo ============================================================
echo   STEP 3: Validation
echo ============================================================
echo   Testing wear.exe with a hello world program...
echo.

:: Create test file
echo var msg = "WeaR v1.0 is Alive!" > hello.wr
echo cetak msg >> hello.wr
echo cetak "Self-Hosting Complete!" >> hello.wr

:: Compile with the new wear.exe
copy /y hello.wr input.wr >nul 2>&1
wear.exe

if errorlevel 1 (
    echo ERROR: wear.exe failed to compile hello.wr!
    exit /b 1
)

if not exist "output.c" (
    echo ERROR: wear.exe did not generate output.c!
    exit /b 1
)

echo   [OK] wear.exe generated output.c
echo   Compiling and running hello world...

gcc -O2 -o hello.exe output.c

if errorlevel 1 (
    echo ERROR: GCC compilation of hello output failed!
    exit /b 1
)

echo.
echo   --- OUTPUT FROM WEAR V1.0 ---
hello.exe
echo   ----------------------------

echo.
echo ============================================================
echo   STEP 4: Cleanup
echo ============================================================
echo   Removing temporary build artifacts...
echo.

:: Cleanup temporary files
if exist "stage1.c" del stage1.c
if exist "stage2.c" del stage2.c
if exist "compiler_gen1.exe" del compiler_gen1.exe
if exist "hello.wr" del hello.wr
if exist "hello.exe" del hello.exe
if exist "output.c" del output.c

echo   [OK] Temporary files cleaned

echo.
echo ============================================================
echo.
echo   ██╗    ██╗███████╗ █████╗ ██████╗     ██╗   ██╗ ██╗
echo   ██║    ██║██╔════╝██╔══██╗██╔══██╗    ██║   ██║███║
echo   ██║ █╗ ██║█████╗  ███████║██████╔╝    ██║   ██║╚██║
echo   ██║███╗██║██╔══╝  ██╔══██║██╔══██╗    ╚██╗ ██╔╝ ██║
echo   ╚███╔███╔╝███████╗██║  ██║██║  ██║     ╚████╔╝  ██║
echo    ╚══╝╚══╝ ╚══════╝╚═╝  ╚═╝╚═╝  ╚═╝      ╚═══╝   ╚═╝
echo.
echo   BOOTSTRAPPING COMPLETE!
echo.
echo   The self-hosted WeaR Lang v1.0 compiler is ready:
echo.
echo     wear.exe  -  Official WeaR Lang Compiler
echo.
echo   The bootstrap compiler (wearc.exe) has been preserved
echo   as a backup. You may delete it when ready.
echo.
echo   Usage:
echo     1. Write your code in 'input.wr'
echo     2. Run: wear.exe
echo     3. Compile output: gcc -o program.exe output.c
echo     4. Run: program.exe
echo.
echo ============================================================
echo.

endlocal
exit /b 0
