/* Generated by WeaR Lang Stage-0 Compiler */
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

int main(int argc, char* argv[]) {
    int x = 0;
    while (x < 5) {
        printf("Hitung native: %d\n", x);
        x = x + 1;
    }
    printf("Selesai!\n");

    return 0;
}
