/* Generated by WeaR Lang Stage-0 Compiler */
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

// User-defined functions
int hitung(int a, int b) {
    printf("Menghitung...\n");
    return a + b;
}

int main(int argc, char* argv[]) {
    int hasil = hitung(10, 5);
    printf("Hasil fungsi: %d\n", hasil);

    return 0;
}
