/* Generated by WeaR Lang Stage-0 Compiler */

/* ============================================================
 * WeaR Lang Runtime Library
 * ============================================================ */

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

/* String concatenation helper */
char* __wear_concat(const char* a, const char* b) {
    size_t len_a = strlen(a);
    size_t len_b = strlen(b);
    char* result = (char*)malloc(len_a + len_b + 1);
    if (result == NULL) {
        fprintf(stderr, "Error: Memory allocation failed\n");
        exit(1);
    }
    strcpy(result, a);
    strcat(result, b);
    return result;
}

/* Integer to string helper */
char* __wear_int_to_str(int value) {
    char* buffer = (char*)malloc(32);
    if (buffer == NULL) {
        fprintf(stderr, "Error: Memory allocation failed\n");
        exit(1);
    }
    sprintf(buffer, "%d", value);
    return buffer;
}

/* String + int concatenation */
char* __wear_concat_str_int(const char* s, int n) {
    char* num_str = __wear_int_to_str(n);
    char* result = __wear_concat(s, num_str);
    free(num_str);
    return result;
}

/* Int + string concatenation */
char* __wear_concat_int_str(int n, const char* s) {
    char* num_str = __wear_int_to_str(n);
    char* result = __wear_concat(num_str, s);
    free(num_str);
    return result;
}

/* Read file contents */
char* __wear_read_file(const char* filename) {
    FILE* file = fopen(filename, "rb");
    if (file == NULL) {
        fprintf(stderr, "Error: Cannot open file '%s'\n", filename);
        return (char*)malloc(1);  /* Return empty string */
    }
    
    fseek(file, 0, SEEK_END);
    long length = ftell(file);
    fseek(file, 0, SEEK_SET);
    
    char* content = (char*)malloc(length + 1);
    if (content == NULL) {
        fprintf(stderr, "Error: Memory allocation failed\n");
        fclose(file);
        exit(1);
    }
    
    fread(content, 1, length, file);
    content[length] = '\0';
    fclose(file);
    
    return content;
}

/* Write file contents */
void __wear_write_file(const char* filename, const char* content) {
    FILE* file = fopen(filename, "wb");
    if (file == NULL) {
        fprintf(stderr, "Error: Cannot write to file '%s'\n", filename);
        return;
    }
    
    fwrite(content, 1, strlen(content), file);
    fclose(file);
}

/* Print string */
void __wear_print_str(const char* s) {
    printf("%s\n", s);
}

/* Print integer */
void __wear_print_int(int n) {
    printf("%d\n", n);
}

/* ============================================================ */

int main(int argc, char* argv[]) {
    char* konten = "Ini data rahasia dari WeaR Lang";
    __wear_write_file("rahasia.txt", konten);
    char* dibaca = __wear_read_file("rahasia.txt");
    __wear_print_str(__wear_concat("Isi file: ", dibaca));

    return 0;
}
