/* Generated by WeaR Lang Self-Hosted Transpiler */

/* ============================================================
 * WeaR Lang Runtime Library
 * ============================================================
 * This file contains C helper functions required by WeaR programs.
 * It is injected into generated C code by the WeaR transpiler.
 * ============================================================ */

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdarg.h>

/* ============================================================
 * Array Operations
 * ============================================================ */

/* Create integer array dynamically */
int* __wear_create_int_array(int count, ...) {
    int* arr = (int*)malloc(count * sizeof(int));
    if (arr == NULL) {
        fprintf(stderr, "Error: Memory allocation failed\n");
        exit(1);
    }
    
    va_list args;
    va_start(args, count);
    for (int i = 0; i < count; i++) {
        arr[i] = va_arg(args, int);
    }
    va_end(args);
    
    return arr;
}

/* ============================================================ 
 * String Operations
 * ============================================================ */

/* Implementation of string + string */
char* __wear_concat_impl(const char* a, const char* b) {
    size_t len_a = strlen(a);
    size_t len_b = strlen(b);
    char* result = (char*)malloc(len_a + len_b + 1);
    if (result == NULL) {
        fprintf(stderr, "Error: Memory allocation failed\n");
        exit(1);
    }
    strcpy(result, a);
    strcat(result, b);
    return result;
}

/* Integer to string helper */
char* __wear_int_to_str(int value) {
    char* buffer = (char*)malloc(32);
    if (buffer == NULL) {
        fprintf(stderr, "Error: Memory allocation failed\n");
        exit(1);
    }
    sprintf(buffer, "%d", value);
    return buffer;
}

/* String + int concatenation */
char* __wear_concat_str_int(const char* s, int n) {
    char* num_str = __wear_int_to_str(n);
    char* result = __wear_concat_impl(s, num_str);
    free(num_str);
    return result;
}

/* Generic macro for overload */
#define __wear_concat(a, b) _Generic((b), \
    int: __wear_concat_str_int, \
    char*: __wear_concat_impl, \
    const char*: __wear_concat_impl \
)(a, b)

/* Int + string concatenation */
char* __wear_concat_int_str(int n, const char* s) {
    char* num_str = __wear_int_to_str(n);
    char* result = __wear_concat(num_str, s);
    free(num_str);
    return result;
}

/* String comparison (returns 1 if equal, 0 otherwise) */
int __wear_streq(const char* a, const char* b) {
    return strcmp(a, b) == 0 ? 1 : 0;
}

/* String length */
int __wear_strlen(const char* s) {
    return (int)strlen(s);
}

/* Character at index (returns 1-char string) */
char* __wear_char_at(const char* s, int index) {
    char* result = (char*)malloc(2);
    if (result == NULL) {
        fprintf(stderr, "Error: Memory allocation failed\n");
        exit(1);
    }
    if (index >= 0 && index < (int)strlen(s)) {
        result[0] = s[index];
        result[1] = '\0';
    } else {
        result[0] = '\0';
    }
    return result;
}

/* Check if character is a quote (returns 1 if quote, 0 otherwise) */
int __wear_is_quote(const char* s) {
    if (s == NULL || s[0] == '\0') return 0;
    return s[0] == '"' ? 1 : 0;
}

/* Get quote character as a string */
char* __wear_quote_char() {
    char* result = (char*)malloc(2);
    result[0] = '"';
    result[1] = '\0';
    return result;
}

/* Get newline character as a string */
char* __wear_newline_char() {
    char* result = (char*)malloc(2);
    result[0] = '\n';
    result[1] = '\0';
    return result;
}

/* Check if character is a newline (returns 1 if newline, 0 otherwise) */
int __wear_is_newline(const char* s) {
    if (s == NULL || s[0] == '\0') return 0;
    return (s[0] == '\n' || s[0] == '\r') ? 1 : 0;
}

/* ============================================================
 * File I/O Operations
 * ============================================================ */

/* Read file contents */
char* __wear_read_file(const char* filename) {
    FILE* file = fopen(filename, "rb");
    if (file == NULL) {
        fprintf(stderr, "Error: Cannot open file '%s'\n", filename);
        return (char*)malloc(1);  /* Return empty string */
    }
    
    fseek(file, 0, SEEK_END);
    long length = ftell(file);
    fseek(file, 0, SEEK_SET);
    
    char* content = (char*)malloc(length + 1);
    if (content == NULL) {
        fprintf(stderr, "Error: Memory allocation failed\n");
        fclose(file);
        exit(1);
    }
    
    fread(content, 1, length, file);
    content[length] = '\0';
    fclose(file);
    
    return content;
}

/* Write file contents */
void __wear_write_file(const char* filename, const char* content) {
    FILE* file = fopen(filename, "wb");
    if (file == NULL) {
        fprintf(stderr, "Error: Cannot write to file '%s'\n", filename);
        return;
    }
    
    fwrite(content, 1, strlen(content), file);
    fclose(file);
}

/* ============================================================
 * Input Operations
 * ============================================================ */

/* Input from user */
char* __wear_input(const char* prompt) {
    if (prompt != NULL && prompt[0] != '\0') {
        printf("%s", prompt);
        fflush(stdout);
    }
    
    char* buffer = (char*)malloc(256);
    if (buffer == NULL) {
        fprintf(stderr, "Error: Memory allocation failed\n");
        exit(1);
    }
    
    if (fgets(buffer, 256, stdin) != NULL) {
        size_t len = strlen(buffer);
        if (len > 0 && buffer[len-1] == '\n') {
            buffer[len-1] = '\0';
        }
    } else {
        buffer[0] = '\0';
    }
    
    return buffer;
}

/* ============================================================
 * Print Operations
 * ============================================================ */

/* Print string */
void __wear_print_str(const char* s) {
    printf("%s\n", s);
}

/* Print integer */
void __wear_print_int(int n) {
    printf("%d\n", n);
}

/* ============================================================ */

/* Forward declarations for self-hosted compiler functions */
char* process_imports(char* src);
int is_string_varname(char* name);
int returns_string(char* fn);
int returns_int(char* fn);
int is_quote(char* c);
int is_newline(char* c);
int is_digit(char* c);
int is_letter(char* c);
int is_space(char* c);


int is_digit(char* c)  {

    if (__wear_streq(c,  "0"))  { return 1 ;}

    if (__wear_streq(c,  "1"))  { return 1 ;}

    if (__wear_streq(c,  "2"))  { return 1 ;}

    if (__wear_streq(c,  "3"))  { return 1 ;}

    if (__wear_streq(c,  "4"))  { return 1 ;}

    if (__wear_streq(c,  "5"))  { return 1 ;}

    if (__wear_streq(c,  "6"))  { return 1 ;}

    if (__wear_streq(c,  "7"))  { return 1 ;}

    if (__wear_streq(c,  "8"))  { return 1 ;}

    if (__wear_streq(c,  "9"))  { return 1 ;}

    return 0;

}
int is_letter(char* c)  {

    if (__wear_streq(c,  "a"))  { return 1 ;}

    if (__wear_streq(c,  "b"))  { return 1 ;}

    if (__wear_streq(c,  "c"))  { return 1 ;}

    if (__wear_streq(c,  "d"))  { return 1 ;}

    if (__wear_streq(c,  "e"))  { return 1 ;}

    if (__wear_streq(c,  "f"))  { return 1 ;}

    if (__wear_streq(c,  "g"))  { return 1 ;}

    if (__wear_streq(c,  "h"))  { return 1 ;}

    if (__wear_streq(c,  "i"))  { return 1 ;}

    if (__wear_streq(c,  "j"))  { return 1 ;}

    if (__wear_streq(c,  "k"))  { return 1 ;}

    if (__wear_streq(c,  "l"))  { return 1 ;}

    if (__wear_streq(c,  "m"))  { return 1 ;}

    if (__wear_streq(c,  "n"))  { return 1 ;}

    if (__wear_streq(c,  "o"))  { return 1 ;}

    if (__wear_streq(c,  "p"))  { return 1 ;}

    if (__wear_streq(c,  "q"))  { return 1 ;}

    if (__wear_streq(c,  "r"))  { return 1 ;}

    if (__wear_streq(c,  "s"))  { return 1 ;}

    if (__wear_streq(c,  "t"))  { return 1 ;}

    if (__wear_streq(c,  "u"))  { return 1 ;}

    if (__wear_streq(c,  "v"))  { return 1 ;}

    if (__wear_streq(c,  "w"))  { return 1 ;}

    if (__wear_streq(c,  "x"))  { return 1 ;}

    if (__wear_streq(c,  "y"))  { return 1 ;}

    if (__wear_streq(c,  "z"))  { return 1 ;}

    if (__wear_streq(c,  "A"))  { return 1 ;}

    if (__wear_streq(c,  "B"))  { return 1 ;}

    if (__wear_streq(c,  "C"))  { return 1 ;}

    if (__wear_streq(c,  "D"))  { return 1 ;}

    if (__wear_streq(c,  "E"))  { return 1 ;}

    if (__wear_streq(c,  "F"))  { return 1 ;}

    if (__wear_streq(c,  "G"))  { return 1 ;}

    if (__wear_streq(c,  "H"))  { return 1 ;}

    if (__wear_streq(c,  "I"))  { return 1 ;}

    if (__wear_streq(c,  "J"))  { return 1 ;}

    if (__wear_streq(c,  "K"))  { return 1 ;}

    if (__wear_streq(c,  "L"))  { return 1 ;}

    if (__wear_streq(c,  "M"))  { return 1 ;}

    if (__wear_streq(c,  "N"))  { return 1 ;}

    if (__wear_streq(c,  "O"))  { return 1 ;}

    if (__wear_streq(c,  "P"))  { return 1 ;}

    if (__wear_streq(c,  "Q"))  { return 1 ;}

    if (__wear_streq(c,  "R"))  { return 1 ;}

    if (__wear_streq(c,  "S"))  { return 1 ;}

    if (__wear_streq(c,  "T"))  { return 1 ;}

    if (__wear_streq(c,  "U"))  { return 1 ;}

    if (__wear_streq(c,  "V"))  { return 1 ;}

    if (__wear_streq(c,  "W"))  { return 1 ;}

    if (__wear_streq(c,  "X"))  { return 1 ;}

    if (__wear_streq(c,  "Y"))  { return 1 ;}

    if (__wear_streq(c,  "Z"))  { return 1 ;}

    if (__wear_streq(c,  "_"))  { return 1 ;}

    return 0;

}
int is_space(char* c)  {

    if (__wear_streq(c,  " "))  { return 1 ;}

    return 0;

}
int returns_int(char* fn)  {

    if (__wear_streq(fn,  "panjang"))  { return 1 ;}

    if (__wear_streq(fn,  "sama"))  { return 1 ;}

    if (__wear_streq(fn,  "is_quote"))  { return 1 ;}

    if (__wear_streq(fn,  "is_newline"))  { return 1 ;}

    if (__wear_streq(fn,  "is_digit"))  { return 1 ;}

    if (__wear_streq(fn,  "is_letter"))  { return 1 ;}

    if (__wear_streq(fn,  "is_space"))  { return 1 ;}

    if (__wear_streq(fn,  "returns_int"))  { return 1 ;}

    if (__wear_streq(fn,  "returns_string"))  { return 1 ;}

    if (__wear_streq(fn,  "is_string_varname"))  { return 1 ;}

    return 0;

}
int returns_string(char* fn)  {

    if (__wear_streq(fn,  "baca_file"))  { return 1 ;}

    if (__wear_streq(fn,  "char_at"))  { return 1 ;}

    if (__wear_streq(fn,  "quote_char"))  { return 1 ;}

    if (__wear_streq(fn,  "newline_char"))  { return 1 ;}

    if (__wear_streq(fn,  "input"))  { return 1 ;}

    if (__wear_streq(fn,  "process_imports"))  { return 1 ;}

    return 0;

}
int is_string_varname(char* name)  {

    

    if (__wear_streq(name,  "pending_concat"))  { return 0 ;}

    if (__wear_streq(name,  "peek_i"))  { return 0 ;}

    if (__wear_streq(name,  "peek_scan"))  { return 0 ;}

    if (__wear_streq(name,  "i"))  { return 0 ;}

    if (__wear_streq(name,  "len"))  { return 0 ;}

    if (__wear_streq(name,  "done"))  { return 0 ;}

    if (__wear_streq(name,  "found_plus"))  { return 0 ;}

    if (__wear_streq(name,  "peek_idx"))  { return 0 ;}

    if (__wear_streq(name,  "func_brace_depth"))  { return 0 ;}

    if (__wear_streq(name,  "read_fn"))  { return 0 ;}

    if (__wear_streq(name,  "read_param"))  { return 0 ;}

    if (__wear_streq(name,  "first_param"))  { return 0 ;}



     int len = __wear_strlen(name);

    if (len  >=  3)  {

         char* p1 = __wear_char_at(name,  0);

         char* p2 = __wear_char_at(name,  1);

         char* p3 = __wear_char_at(name,  2);

        

        if (__wear_streq(p1,  "m"))  {

            if (__wear_streq(p2,  "s"))  {

                if (__wear_streq(p3,  "g"))  { return 1 ;}

            }

        }

        

        if (__wear_streq(p1,  "s"))  {

            if (__wear_streq(p2,  "t"))  {

                if (__wear_streq(p3,  "r"))  { return 1 ;}

            }

        }

    }



    if (len  >=  4)  {

         char* p1 = __wear_char_at(name,  0);

         char* p2 = __wear_char_at(name,  1);

         char* p3 = __wear_char_at(name,  2);

         char* p4 = __wear_char_at(name,  3);

        

        if (__wear_streq(p1,  "s"))  {

            if (__wear_streq(p2,  "t"))  {

                if (__wear_streq(p3,  "r"))  { return 1 ;}

            }

            if (__wear_streq(p2,  "o"))  { return 1 ;}

            if (__wear_streq(p2,  "c"))  { return 1 ;}

        }

        

        if (__wear_streq(p1,  "f"))  {

            if (__wear_streq(p2,  "i"))  { return 1 ;}

            if (__wear_streq(p2,  "u"))  { return 1 ;}

        }

        

        if (__wear_streq(p1,  "o"))  {

            if (__wear_streq(p2,  "u"))  { return 1 ;}

        }

        

        if (__wear_streq(p1,  "w"))  {

            if (__wear_streq(p2,  "o"))  { return 1 ;}

        }

        

        if (__wear_streq(p1,  "r"))  {

            if (__wear_streq(p2,  "u"))  { return 1 ;}

            if (__wear_streq(p2,  "e"))  { return 1 ;}

        }

        

        if (__wear_streq(p1,  "t"))  {

            if (__wear_streq(p2,  "e"))  { return 1 ;}

            if (__wear_streq(p2,  "o"))  { return 1 ;}

        }

        

        if (__wear_streq(p1,  "p"))  {

            if (__wear_streq(p2,  "e"))  { return 1 ;}

            if (__wear_streq(p2,  "a"))  { return 1 ;}

        }

        

        if (__wear_streq(p1,  "g"))  {

            if (__wear_streq(p2,  "l"))  { return 1 ;}

            if (__wear_streq(p2,  "a"))  { return 1 ;}

        }

        

        if (__wear_streq(p1,  "m"))  {

            if (__wear_streq(p2,  "a"))  { return 1 ;}

        }

        

        if (__wear_streq(p1,  "c"))  {

            if (__wear_streq(p2,  "o"))  { return 1 ;}

        }

        

        if (__wear_streq(p1,  "b"))  {

            if (__wear_streq(p2,  "u"))  { return 1 ;}

        }

        

        if (__wear_streq(p1,  "n"))  {

            if (__wear_streq(p2,  "a"))  { return 1 ;}

            if (__wear_streq(p2,  "l"))  { return 1 ;}

        }

        

        if (__wear_streq(p1,  "v"))  {

            if (__wear_streq(p2,  "a"))  { return 1 ;}

        }

        

        if (__wear_streq(p1,  "e"))  {

            if (__wear_streq(p2,  "x"))  { return 1 ;}

        }

    }

    if (len  >=  2)  {

         char* p1 = __wear_char_at(name,  0);

         char* p2 = __wear_char_at(name,  1);

        if (__wear_streq(p1,  "n"))  {

            if (__wear_streq(p2,  "l"))  { return 1 ;}

        }

    }



    if (__wear_streq(name,  "c"))  { return 1 ;}

    if (__wear_streq(name,  "q"))  { return 1 ;}

    if (__wear_streq(name,  "next"))  { return 1 ;}

    if (__wear_streq(name,  "num"))  { return 1 ;} 

    return 0;

}
char* process_imports(char* src)  {

     char* buffer = "";

     int idx = 0;

     int total = __wear_strlen(src);

     int at_line_start = 1;

    

    while (idx  <  total)  {

         char* ch = __wear_char_at(src,  idx);

        

        

        if (__wear_is_newline(ch))  {

            buffer  =  __wear_concat(buffer ,  ch);

            idx  =  idx  +  1;

            at_line_start  =  1;

        } else if (is_space(ch))  {

            buffer  =  __wear_concat(buffer ,  ch);

            idx  =  idx  +  1;

            

        } else if (__wear_streq(ch,  "i"))  {

            

            if (at_line_start  ==  1)  {

                

                 char* word = "";

                 int j = idx;

                while (j  <  total)  {

                     char* jc = __wear_char_at(src,  j);

                    if (is_letter(jc))  {

                        word  =  __wear_concat(word ,  jc);

                        j  =  j  +  1;

                    } else  {

                        j  =  total;

                    }

                }

                

                if (__wear_streq(word,  "impor"))  {

                    

                    idx  =  idx  +  5;

                    

                    

                     int skipping = 1;

                    while (skipping  ==  1)  {

                        if (idx  >=  total)  {

                            skipping  =  0;

                        } else  {

                             char* wc = __wear_char_at(src,  idx);

                            if (is_space(wc))  {

                                idx  =  idx  +  1;

                            } else  {

                                skipping  =  0;

                            }

                        }

                    }

                    

                    

                     char* qc = __wear_char_at(src,  idx);

                    if (__wear_is_quote(qc))  {

                        idx  =  idx  +  1;

                         char* filename = "";

                         int reading = 1;

                        while (reading  ==  1)  {

                            if (idx  >=  total)  {

                                reading  =  0;

                            } else  {

                                 char* fc = __wear_char_at(src,  idx);

                                if (__wear_is_quote(fc))  {

                                    reading  =  0;

                                    idx  =  idx  +  1;

                                } else  {

                                    filename  =  __wear_concat(filename ,  fc);

                                    idx  =  idx  +  1;

                                }

                            }

                        }

                        

                        

                         char* lib = __wear_read_file(filename);

                         char* content = process_imports(lib);

                        buffer  =  __wear_concat(buffer ,  content);

                        buffer  =  __wear_concat(buffer ,  __wear_newline_char());

                    }

                } else  {

                    buffer  =  __wear_concat(buffer ,  ch);

                    idx  =  idx  +  1;

                    at_line_start  =  0;

                }

            } else  {

                buffer  =  __wear_concat(buffer ,  ch);

                idx  =  idx  +  1;

                at_line_start  =  0;

            }

        } else  {

            buffer  =  __wear_concat(buffer ,  ch);

            idx  =  idx  +  1;

            at_line_start  =  0;

        }

    }

    

    return buffer;

}

int main() {




























































__wear_print_str("=== WeaR Lang Self-Hosted Transpiler ===");

__wear_print_str("Reading: input.wr");



 char* raw_src = __wear_read_file("input.wr");

 char* source = process_imports(raw_src);

 int len = __wear_strlen(source);

 int i = 0;

 int done = 0;



__wear_print_str("Loading: runtime.c");

 char* runtime_code = __wear_read_file("runtime.c");





 char* global_code = "";

 char* main_code = "";

 char* nl = __wear_newline_char();





 int inside_func = 0;

 int func_brace_depth = 0;

 int need_semi = 0;

 int in_print = 0;

 int print_type = 0;

 int in_var_decl = 0;

 char* var_name = "";





 char* last_operand = "";

 int pending_concat = 0;

 int concat_depth = 0;



while (done  ==  0)  {

    if (i  >=  len)  {

        done  =  1;

    } else  {

         char* c = __wear_char_at(source,  i);

        

        if (is_space(c))  {

            if (inside_func  ==  1)  {

                global_code  =  __wear_concat(global_code ,  " ");

            } else  {

                main_code  =  __wear_concat(main_code ,  " ");

            }

            i  =  i  +  1;

        } else if (__wear_is_newline(c))  {

            if (need_semi  ==  1)  {

                

                while (pending_concat  >  0)  {

                    if (inside_func  ==  1)  {

                        global_code  =  __wear_concat(global_code ,  ")");

                    } else  {

                        main_code  =  __wear_concat(main_code ,  ")");

                    }

                    pending_concat  =  pending_concat  -  1;

                }

                if (in_print  ==  1)  {

                    if (inside_func  ==  1)  {

                        global_code  =  __wear_concat(global_code ,  ");");

                    } else  {

                        main_code  =  __wear_concat(main_code ,  ");");

                    }

                    in_print  =  0;

                } else  {

                    if (inside_func  ==  1)  {

                        global_code  =  __wear_concat(global_code ,  ";");

                    } else  {

                        main_code  =  __wear_concat(main_code ,  ";");

                    }

                }

                need_semi  =  0;

            }

            if (inside_func  ==  1)  {

                global_code  =  __wear_concat(global_code ,  nl);

            } else  {

                main_code  =  __wear_concat(main_code ,  nl);

            }

            in_var_decl  =  0;

            pending_concat  =  0;

            last_operand  =  "";

            i  =  i  +  1;

        } else if (__wear_is_quote(c))  {

             char* str_content = "";

            i  =  i  +  1;

             int scan_str = 1;

            while (scan_str  ==  1)  {

                if (i  >=  len)  {

                    scan_str  =  0;

                } else  {

                     char* next = __wear_char_at(source,  i);

                    if (__wear_is_quote(next))  {

                        scan_str  =  0;

                        i  =  i  +  1;

                    } else  {

                        str_content  =  __wear_concat(str_content ,  next);

                        i  =  i  +  1;

                    }

                }

            }

             char* q = __wear_quote_char();

            

            

            

            

             int peek_idx = i;

             int found_plus = 0;

            while (peek_idx  <  len)  {

                 char* peek_ch = __wear_char_at(source,  peek_idx);

                if (is_space(peek_ch))  {

                    peek_idx  =  peek_idx  +  1;

                } else if (__wear_streq(peek_ch,  "+"))  {

                    found_plus  =  1;

                    peek_idx  =  len;

                } else  {

                    peek_idx  =  len;

                }

            }



            if (in_var_decl  ==  1)  {

                if (inside_func  ==  1)  {

                    global_code  =  __wear_concat(global_code ,  "char* ");

                    global_code  =  __wear_concat(global_code ,  var_name);

                    global_code  =  __wear_concat(global_code ,  " = ");

                    

                    if (found_plus  ==  1)  {

                        global_code  =  __wear_concat(global_code ,  "__wear_concat(");

                        pending_concat  =  pending_concat  +  1;

                    }

                    

                    global_code  =  __wear_concat(global_code ,  q);

                    global_code  =  __wear_concat(global_code ,  str_content);

                    global_code  =  __wear_concat(global_code ,  q);

                } else  {

                    main_code  =  __wear_concat(main_code ,  "char* ");

                    main_code  =  __wear_concat(main_code ,  var_name);

                    main_code  =  __wear_concat(main_code ,  " = ");

                    

                    if (found_plus  ==  1)  {

                        main_code  =  __wear_concat(main_code ,  "__wear_concat(");

                        pending_concat  =  pending_concat  +  1;

                    }



                    main_code  =  __wear_concat(main_code ,  q);

                    main_code  =  __wear_concat(main_code ,  str_content);

                    main_code  =  __wear_concat(main_code ,  q);

                }

                in_var_decl  =  0;

            } else  {

                if (inside_func  ==  1)  {

                    if (found_plus  ==  1)  {

                        global_code  =  __wear_concat(global_code ,  "__wear_concat(");

                        pending_concat  =  pending_concat  +  1;

                    }

                    global_code  =  __wear_concat(global_code ,  q);

                    global_code  =  __wear_concat(global_code ,  str_content);

                    global_code  =  __wear_concat(global_code ,  q);

                } else  {

                    if (found_plus  ==  1)  {

                        main_code  =  __wear_concat(main_code ,  "__wear_concat(");

                        pending_concat  =  pending_concat  +  1;

                    }

                    main_code  =  __wear_concat(main_code ,  q);

                    main_code  =  __wear_concat(main_code ,  str_content);

                    main_code  =  __wear_concat(main_code ,  q);

                }

            }

            need_semi  =  1;

        } else if (__wear_streq(c,  "="))  {

            if (in_var_decl  ==  1)  {

                i  =  i  +  1;

                 int skip_sp = 1;

                while (skip_sp  ==  1)  {

                    if (i  >=  len)  {

                        skip_sp  =  0;

                    } else  {

                         char* next = __wear_char_at(source,  i);

                        if (is_space(next))  {

                            i  =  i  +  1;

                        } else  {

                            skip_sp  =  0;

                        }

                    }

                }

                 char* peek_c = __wear_char_at(source,  i);

                if (__wear_is_quote(peek_c))  {

                    

                } else if (is_digit(peek_c))  {

                    if (inside_func  ==  1)  {

                        global_code  =  __wear_concat(global_code ,  "int ");

                        global_code  =  __wear_concat(global_code ,  var_name);

                        global_code  =  __wear_concat(global_code ,  " = ");

                    } else  {

                        main_code  =  __wear_concat(main_code ,  "int ");

                        main_code  =  __wear_concat(main_code ,  var_name);

                        main_code  =  __wear_concat(main_code ,  " = ");

                    }

                    in_var_decl  =  0;

                } else if (is_letter(peek_c))  {

                     char* peek_word = "";

                     int peek_i = i;

                     int peek_scan = 1;

                    while (peek_scan  ==  1)  {

                        if (peek_i  >=  len)  {

                            peek_scan  =  0;

                        } else  {

                             char* peek_next = __wear_char_at(source,  peek_i);

                            if (is_letter(peek_next))  {

                                peek_word  =  __wear_concat(peek_word ,  peek_next);

                                peek_i  =  peek_i  +  1;

                            } else if (is_digit(peek_next))  {

                                peek_word  =  __wear_concat(peek_word ,  peek_next);

                                peek_i  =  peek_i  +  1;

                            } else  {

                                peek_scan  =  0;

                            }

                        }

                    }

                    if (returns_int(peek_word))  {

                        if (inside_func  ==  1)  {

                            global_code  =  __wear_concat(global_code ,  "int ");

                            global_code  =  __wear_concat(global_code ,  var_name);

                            global_code  =  __wear_concat(global_code ,  " = ");

                        } else  {

                            main_code  =  __wear_concat(main_code ,  "int ");

                            main_code  =  __wear_concat(main_code ,  var_name);

                            main_code  =  __wear_concat(main_code ,  " = ");

                        }

                        in_var_decl  =  0;

                    } else if (returns_string(peek_word))  {

                        if (inside_func  ==  1)  {

                            global_code  =  __wear_concat(global_code ,  "char* ");

                            global_code  =  __wear_concat(global_code ,  var_name);

                            global_code  =  __wear_concat(global_code ,  " = ");

                        } else  {

                            main_code  =  __wear_concat(main_code ,  "char* ");

                            main_code  =  __wear_concat(main_code ,  var_name);

                            main_code  =  __wear_concat(main_code ,  " = ");

                        }

                        in_var_decl  =  0;

                    } else  {

                        if (is_string_varname(peek_word))  {

                            if (inside_func  ==  1)  {

                                global_code  =  __wear_concat(global_code ,  "char* ");

                                global_code  =  __wear_concat(global_code ,  var_name);

                                global_code  =  __wear_concat(global_code ,  " = ");

                            } else  {

                                main_code  =  __wear_concat(main_code ,  "char* ");

                                main_code  =  __wear_concat(main_code ,  var_name);

                                main_code  =  __wear_concat(main_code ,  " = ");

                            }

                        } else if (is_string_varname(var_name))  {

                            if (inside_func  ==  1)  {

                                global_code  =  __wear_concat(global_code ,  "char* ");

                                global_code  =  __wear_concat(global_code ,  var_name);

                                global_code  =  __wear_concat(global_code ,  " = ");

                            } else  {

                                main_code  =  __wear_concat(main_code ,  "char* ");

                                main_code  =  __wear_concat(main_code ,  var_name);

                                main_code  =  __wear_concat(main_code ,  " = ");

                            }

                        } else  {

                            if (inside_func  ==  1)  {

                                global_code  =  __wear_concat(global_code ,  "int ");

                                global_code  =  __wear_concat(global_code ,  var_name);

                                global_code  =  __wear_concat(global_code ,  " = ");

                            } else  {

                                main_code  =  __wear_concat(main_code ,  "int ");

                                main_code  =  __wear_concat(main_code ,  var_name);

                                main_code  =  __wear_concat(main_code ,  " = ");

                            }

                        }

                        in_var_decl  =  0;

                    }

                } else  {

                    if (inside_func  ==  1)  {

                        global_code  =  __wear_concat(global_code ,  "int ");

                        global_code  =  __wear_concat(global_code ,  var_name);

                        global_code  =  __wear_concat(global_code ,  " = ");

                    } else  {

                        main_code  =  __wear_concat(main_code ,  "int ");

                        main_code  =  __wear_concat(main_code ,  var_name);

                        main_code  =  __wear_concat(main_code ,  " = ");

                    }

                    in_var_decl  =  0;

                }

            } else  {

                

                 int next_i = i  +  1;

                if (next_i  <  len)  {

                     char* next_c = __wear_char_at(source,  next_i);

                    if (__wear_streq(next_c,  "="))  {

                        if (inside_func  ==  1)  {

                            global_code  =  __wear_concat(global_code ,  " == ");

                        } else  {

                            main_code  =  __wear_concat(main_code ,  " == ");

                        }

                        i  =  i  +  2;

                    } else  {

                        if (inside_func  ==  1)  {

                            global_code  =  __wear_concat(global_code ,  " = ");

                        } else  {

                            main_code  =  __wear_concat(main_code ,  " = ");

                        }

                        i  =  i  +  1;

                    }

                } else  {

                    if (inside_func  ==  1)  {

                        global_code  =  __wear_concat(global_code ,  " = ");

                    } else  {

                        main_code  =  __wear_concat(main_code ,  " = ");

                    }

                    i  =  i  +  1;

                }

            }

        } else if (__wear_streq(c,  "+"))  {

            

            if (pending_concat  >  0)  {

                if (inside_func  ==  1)  {

                    global_code  =  __wear_concat(global_code ,  ", ");

                } else  {

                    main_code  =  __wear_concat(main_code ,  ", ");

                }

            } else  {

                if (inside_func  ==  1)  {

                    global_code  =  __wear_concat(global_code ,  " + ");

                } else  {

                    main_code  =  __wear_concat(main_code ,  " + ");

                }

            }

            i  =  i  +  1;

        } else if (__wear_streq(c,  "-"))  {

            if (inside_func  ==  1)  {

                global_code  =  __wear_concat(global_code ,  " - ");

            } else  {

                main_code  =  __wear_concat(main_code ,  " - ");

            }

            i  =  i  +  1;

        } else if (__wear_streq(c,  "*"))  {

            if (inside_func  ==  1)  {

                global_code  =  __wear_concat(global_code ,  " * ");

            } else  {

                main_code  =  __wear_concat(main_code ,  " * ");

            }

            i  =  i  +  1;

        } else if (__wear_streq(c,  "/"))  {

             int next_i = i  +  1;

            if (next_i  <  len)  {

                 char* next_c = __wear_char_at(source,  next_i);

                if (__wear_streq(next_c,  "/"))  {

                    i  =  i  +  2;

                     int skip_comment = 1;

                    while (skip_comment  ==  1)  {

                        if (i  >=  len)  {

                            skip_comment  =  0;

                        } else  {

                             char* comment_c = __wear_char_at(source,  i);

                            if (__wear_is_newline(comment_c))  {

                                skip_comment  =  0;

                            } else  {

                                i  =  i  +  1;

                            }

                        }

                    }

                } else  {

                    if (inside_func  ==  1)  {

                        global_code  =  __wear_concat(global_code ,  " / ");

                    } else  {

                        main_code  =  __wear_concat(main_code ,  " / ");

                    }

                    i  =  i  +  1;

                }

            } else  {

                if (inside_func  ==  1)  {

                    global_code  =  __wear_concat(global_code ,  " / ");

                } else  {

                    main_code  =  __wear_concat(main_code ,  " / ");

                }

                i  =  i  +  1;

            }

        } else if (__wear_streq(c,  "<"))  {

             int next_i = i  +  1;

            if (next_i  <  len)  {

                 char* next_c = __wear_char_at(source,  next_i);

                if (__wear_streq(next_c,  "="))  {

                    if (inside_func  ==  1)  {

                        global_code  =  __wear_concat(global_code ,  " <= ");

                    } else  {

                        main_code  =  __wear_concat(main_code ,  " <= ");

                    }

                    i  =  i  +  2;

                } else  {

                    if (inside_func  ==  1)  {

                        global_code  =  __wear_concat(global_code ,  " < ");

                    } else  {

                        main_code  =  __wear_concat(main_code ,  " < ");

                    }

                    i  =  i  +  1;

                }

            } else  {

                if (inside_func  ==  1)  {

                    global_code  =  __wear_concat(global_code ,  " < ");

                } else  {

                    main_code  =  __wear_concat(main_code ,  " < ");

                }

                i  =  i  +  1;

            }

        } else if (__wear_streq(c,  ">"))  {

             int next_i = i  +  1;

            if (next_i  <  len)  {

                 char* next_c = __wear_char_at(source,  next_i);

                if (__wear_streq(next_c,  "="))  {

                    if (inside_func  ==  1)  {

                        global_code  =  __wear_concat(global_code ,  " >= ");

                    } else  {

                        main_code  =  __wear_concat(main_code ,  " >= ");

                    }

                    i  =  i  +  2;

                } else  {

                    if (inside_func  ==  1)  {

                        global_code  =  __wear_concat(global_code ,  " > ");

                    } else  {

                        main_code  =  __wear_concat(main_code ,  " > ");

                    }

                    i  =  i  +  1;

                }

            } else  {

                if (inside_func  ==  1)  {

                    global_code  =  __wear_concat(global_code ,  " > ");

                } else  {

                    main_code  =  __wear_concat(main_code ,  " > ");

                }

                i  =  i  +  1;

            }

        } else if (__wear_streq(c,  "("))  {

            if (inside_func  ==  1)  {

                global_code  =  __wear_concat(global_code ,  "(");

            } else  {

                main_code  =  __wear_concat(main_code ,  "(");

            }

            i  =  i  +  1;

        } else if (__wear_streq(c,  ")"))  {

            if (inside_func  ==  1)  {

                global_code  =  __wear_concat(global_code ,  ")");

            } else  {

                main_code  =  __wear_concat(main_code ,  ")");

            }

            i  =  i  +  1;

        } else if (__wear_streq(c,  "{"))  {

            if (inside_func  ==  1)  {

                global_code  =  __wear_concat(global_code ,  " {");

                func_brace_depth  =  func_brace_depth  +  1;

            } else  {

                main_code  =  __wear_concat(main_code ,  " {");

            }

            need_semi  =  0;

            i  =  i  +  1;

        } else if (__wear_streq(c,  "}"))  {

            

            if (need_semi  ==  1)  {

                

                while (pending_concat  >  0)  {

                    if (inside_func  ==  1)  {

                        global_code  =  __wear_concat(global_code ,  ")");

                    } else  {

                        main_code  =  __wear_concat(main_code ,  ")");

                    }

                    pending_concat  =  pending_concat  -  1;

                }

                if (in_print  ==  1)  {

                    if (inside_func  ==  1)  {

                        global_code  =  __wear_concat(global_code ,  ");");

                    } else  {

                        main_code  =  __wear_concat(main_code ,  ");");

                    }

                    in_print  =  0;

                } else  {

                    if (inside_func  ==  1)  {

                        global_code  =  __wear_concat(global_code ,  ";");

                    } else  {

                        main_code  =  __wear_concat(main_code ,  ";");

                    }

                }

                need_semi  =  0;

            }

            pending_concat  =  0;

            if (inside_func  ==  1)  {

                func_brace_depth  =  func_brace_depth  -  1;

                global_code  =  __wear_concat(global_code ,  "}");

                if (func_brace_depth  ==  0)  {

                    global_code  =  __wear_concat(global_code ,  nl);

                    inside_func  =  0;

                }

            } else  {

                main_code  =  __wear_concat(main_code ,  "}");

            }

            need_semi  =  0;

            i  =  i  +  1;

        } else if (__wear_streq(c,  ","))  {

            if (inside_func  ==  1)  {

                global_code  =  __wear_concat(global_code ,  ", ");

            } else  {

                main_code  =  __wear_concat(main_code ,  ", ");

            }

            i  =  i  +  1;

        } else if (is_digit(c))  {

             char* num = c;

             int scan_num = 1;

            i  =  i  +  1;

            while (scan_num  ==  1)  {

                if (i  >=  len)  {

                    scan_num  =  0;

                } else  {

                     char* next = __wear_char_at(source,  i);

                    if (is_digit(next))  {

                        num  =  __wear_concat(num ,  next);

                        i  =  i  +  1;

                    } else  {

                        scan_num  =  0;

                    }

                }

            }

            if (inside_func  ==  1)  {

                global_code  =  __wear_concat(global_code ,  num);

            } else  {

                main_code  =  __wear_concat(main_code ,  num);

            }

            need_semi  =  1;

        } else if (is_letter(c))  {

             char* word = c;

             int scan_word = 1;

            i  =  i  +  1;

            while (scan_word  ==  1)  {

                if (i  >=  len)  {

                    scan_word  =  0;

                } else  {

                     char* next = __wear_char_at(source,  i);

                    if (is_letter(next))  {

                        word  =  __wear_concat(word ,  next);

                        i  =  i  +  1;

                    } else if (is_digit(next))  {

                        word  =  __wear_concat(word ,  next);

                        i  =  i  +  1;

                    } else  {

                        scan_word  =  0;

                    }

                }

            }

            

            

            if (__wear_streq(word,  "var"))  {

                in_var_decl  =  1;

                 int skip_sp = 1;

                while (skip_sp  ==  1)  {

                    if (i  >=  len)  {

                        skip_sp  =  0;

                    } else  {

                         char* next = __wear_char_at(source,  i);

                        if (is_space(next))  {

                            i  =  i  +  1;

                        } else  {

                            skip_sp  =  0;

                        }

                    }

                }

                var_name  =  "";

                 int read_name = 1;

                while (read_name  ==  1)  {

                    if (i  >=  len)  {

                        read_name  =  0;

                    } else  {

                         char* next = __wear_char_at(source,  i);

                        if (is_letter(next))  {

                            var_name  =  __wear_concat(var_name ,  next);

                            i  =  i  +  1;

                        } else if (is_digit(next))  {

                            var_name  =  __wear_concat(var_name ,  next);

                            i  =  i  +  1;

                        } else  {

                            read_name  =  0;

                        }

                    }

                }

                need_semi  =  1;

            } else if (__wear_streq(word,  "cetak"))  {

                 int skip_sp = 1;

                while (skip_sp  ==  1)  {

                    if (i  >=  len)  {

                        skip_sp  =  0;

                    } else  {

                         char* next = __wear_char_at(source,  i);

                        if (is_space(next))  {

                            i  =  i  +  1;

                        } else  {

                            skip_sp  =  0;

                        }

                    }

                }

                 char* peek_c = __wear_char_at(source,  i);

                if (__wear_is_quote(peek_c))  {

                    if (inside_func  ==  1)  {

                        global_code  =  __wear_concat(global_code ,  "__wear_print_str(");

                    } else  {

                        main_code  =  __wear_concat(main_code ,  "__wear_print_str(");

                    }

                    print_type  =  1;

                } else if (is_digit(peek_c))  {

                    if (inside_func  ==  1)  {

                        global_code  =  __wear_concat(global_code ,  "__wear_print_int(");

                    } else  {

                        main_code  =  __wear_concat(main_code ,  "__wear_print_int(");

                    }

                    print_type  =  0;

                } else if (is_letter(peek_c))  {

                     char* peek_word = "";

                     int peek_i = i;

                     int peek_scan = 1;

                    while (peek_scan  ==  1)  {

                        if (peek_i  >=  len)  {

                            peek_scan  =  0;

                        } else  {

                             char* peek_next = __wear_char_at(source,  peek_i);

                            if (is_letter(peek_next))  {

                                peek_word  =  __wear_concat(peek_word ,  peek_next);

                                peek_i  =  peek_i  +  1;

                            } else if (is_digit(peek_next))  {

                                peek_word  =  __wear_concat(peek_word ,  peek_next);

                                peek_i  =  peek_i  +  1;

                            } else  {

                                peek_scan  =  0;

                            }

                        }

                    }

                    if (returns_string(peek_word))  {

                        if (inside_func  ==  1)  {

                            global_code  =  __wear_concat(global_code ,  "__wear_print_str(");

                        } else  {

                            main_code  =  __wear_concat(main_code ,  "__wear_print_str(");

                        }

                        print_type  =  1;

                    } else if (is_string_varname(peek_word))  {

                        if (inside_func  ==  1)  {

                            global_code  =  __wear_concat(global_code ,  "__wear_print_str(");

                        } else  {

                            main_code  =  __wear_concat(main_code ,  "__wear_print_str(");

                        }

                        print_type  =  1;

                    } else  {

                        if (inside_func  ==  1)  {

                            global_code  =  __wear_concat(global_code ,  "__wear_print_int(");

                        } else  {

                            main_code  =  __wear_concat(main_code ,  "__wear_print_int(");

                        }

                        print_type  =  0;

                    }

                } else  {

                    if (inside_func  ==  1)  {

                        global_code  =  __wear_concat(global_code ,  "__wear_print_int(");

                    } else  {

                        main_code  =  __wear_concat(main_code ,  "__wear_print_int(");

                    }

                    print_type  =  0;

                }

                in_print  =  1;

                need_semi  =  1;

            } else if (__wear_streq(word,  "selama"))  {

                if (inside_func  ==  1)  {

                    global_code  =  __wear_concat(global_code ,  "while");

                } else  {

                    main_code  =  __wear_concat(main_code ,  "while");

                }

                need_semi  =  0;

            } else if (__wear_streq(word,  "jika"))  {

                if (inside_func  ==  1)  {

                    global_code  =  __wear_concat(global_code ,  "if");

                } else  {

                    main_code  =  __wear_concat(main_code ,  "if");

                }

                need_semi  =  0;

            } else if (__wear_streq(word,  "lainnya"))  {

                if (inside_func  ==  1)  {

                    global_code  =  __wear_concat(global_code ,  "else");

                } else  {

                    main_code  =  __wear_concat(main_code ,  "else");

                }

                need_semi  =  0;

            } else if (__wear_streq(word,  "fungsi"))  {

                

                inside_func  =  1;

                func_brace_depth  =  0;

                

                

                 int skip_sp = 1;

                while (skip_sp  ==  1)  {

                    if (i  >=  len)  {

                        skip_sp  =  0;

                    } else  {

                         char* next = __wear_char_at(source,  i);

                        if (is_space(next))  {

                            i  =  i  +  1;

                        } else  {

                            skip_sp  =  0;

                        }

                    }

                }

                

                 char* func_name = "";

                 int read_fn = 1;

                while (read_fn  ==  1)  {

                    if (i  >=  len)  {

                        read_fn  =  0;

                    } else  {

                         char* next = __wear_char_at(source,  i);

                        if (is_letter(next))  {

                            func_name  =  __wear_concat(func_name ,  next);

                            i  =  i  +  1;

                        } else if (is_digit(next))  {

                            func_name  =  __wear_concat(func_name ,  next);

                            i  =  i  +  1;

                        } else  {

                            read_fn  =  0;

                        }

                    }

                }

                if (returns_string(func_name))  {

                    global_code  =  __wear_concat(global_code ,  "char* ");

                } else  {

                    global_code  =  __wear_concat(global_code ,  "int ");

                }

                global_code  =  __wear_concat(global_code ,  func_name);

                global_code  =  __wear_concat(global_code ,  "(");

                

                 int skip_to_paren = 1;

                while (skip_to_paren  ==  1)  {

                    if (i  >=  len)  {

                        skip_to_paren  =  0;

                    } else  {

                         char* next = __wear_char_at(source,  i);

                        if (__wear_streq(next,  "("))  {

                            i  =  i  +  1;

                            skip_to_paren  =  0;

                        } else  {

                            i  =  i  +  1;

                        }

                    }

                }

                

                 int first_param = 1;

                 int parse_params = 1;

                while (parse_params  ==  1)  {

                     int skip_sp2 = 1;

                    while (skip_sp2  ==  1)  {

                        if (i  >=  len)  {

                            skip_sp2  =  0;

                        } else  {

                             char* next = __wear_char_at(source,  i);

                            if (is_space(next))  {

                                i  =  i  +  1;

                            } else  {

                                skip_sp2  =  0;

                            }

                        }

                    }

                    if (i  >=  len)  {

                        parse_params  =  0;

                    } else  {

                         char* peek = __wear_char_at(source,  i);

                        if (__wear_streq(peek,  ")"))  {

                            parse_params  =  0;

                            i  =  i  +  1;

                        } else if (__wear_streq(peek,  ","))  {

                            i  =  i  +  1;

                        } else if (is_letter(peek))  {

                             char* param_name = "";

                             int read_param = 1;

                            while (read_param  ==  1)  {

                                if (i  >=  len)  {

                                    read_param  =  0;

                                } else  {

                                     char* next = __wear_char_at(source,  i);

                                    if (is_letter(next))  {

                                        param_name  =  __wear_concat(param_name ,  next);

                                        i  =  i  +  1;

                                    } else if (is_digit(next))  {

                                        param_name  =  __wear_concat(param_name ,  next);

                                        i  =  i  +  1;

                                    } else  {

                                        read_param  =  0;

                                    }

                                }

                            }

                            

                            

                             char* ptype = "";

                             int skip_ws = 1;

                            while (skip_ws  ==  1)  {

                                if (i  >=  len)  {

                                    skip_ws  =  0;

                                } else  {

                                     char* wc = __wear_char_at(source,  i);

                                    if (is_space(wc))  {

                                        i  =  i  +  1;

                                    } else  {

                                        skip_ws  =  0;

                                    }

                                }

                            }

                            

                             char* colon_ch = __wear_char_at(source,  i);

                            if (__wear_streq(colon_ch,  ":"))  {

                                i  =  i  +  1;

                                

                                 int skip_ws2 = 1;

                                while (skip_ws2  ==  1)  {

                                    if (i  >=  len)  {

                                        skip_ws2  =  0;

                                    } else  {

                                         char* wc2 = __wear_char_at(source,  i);

                                        if (is_space(wc2))  {

                                            i  =  i  +  1;

                                        } else  {

                                            skip_ws2  =  0;

                                        }

                                    }

                                }

                                

                                 int read_type = 1;

                                while (read_type  ==  1)  {

                                    if (i  >=  len)  {

                                        read_type  =  0;

                                    } else  {

                                         char* tc = __wear_char_at(source,  i);

                                        if (is_letter(tc))  {

                                            ptype  =  ptype  +  tc;

                                            i  =  i  +  1;

                                        } else  {

                                            read_type  =  0;

                                        }

                                    }

                                }

                            }

                            

                            

                             char* ctype_str = "";

                            if (__wear_streq(ptype,  "int"))  {

                                ctype_str  =  "int ";

                            } else if (__wear_streq(ptype,  "str"))  {

                                ctype_str  =  "char* ";

                            } else  {

                                

                                if (is_string_varname(param_name))  {

                                    ctype_str  =  "char* ";

                                } else  {

                                    ctype_str  =  "int ";

                                }

                            }

                            

                            if (first_param  ==  1)  {

                                global_code  =  __wear_concat(global_code ,  ctype_str);

                                global_code  =  __wear_concat(global_code ,  param_name);

                                first_param  =  0;

                            } else  {

                                global_code  =  __wear_concat(global_code ,  ", ");

                                global_code  =  __wear_concat(global_code ,  ctype_str);

                                global_code  =  __wear_concat(global_code ,  param_name);

                            }

                        } else  {

                            i  =  i  +  1;

                        }

                    }

                }

                global_code  =  __wear_concat(global_code ,  ")");

                need_semi  =  0;

            } else if (__wear_streq(word,  "kembalikan"))  {

                if (inside_func  ==  1)  {

                    global_code  =  __wear_concat(global_code ,  "return");

                } else  {

                    main_code  =  __wear_concat(main_code ,  "return");

                }

                need_semi  =  1;

            } else if (__wear_streq(word,  "baca_file"))  {

                if (inside_func  ==  1)  {

                    global_code  =  __wear_concat(global_code ,  "__wear_read_file");

                } else  {

                    main_code  =  __wear_concat(main_code ,  "__wear_read_file");

                }

                need_semi  =  1;

            } else if (__wear_streq(word,  "input"))  {

                if (inside_func  ==  1)  {

                    global_code  =  __wear_concat(global_code ,  "__wear_input");

                } else  {

                    main_code  =  __wear_concat(main_code ,  "__wear_input");

                }

                need_semi  =  1;

            } else if (__wear_streq(word,  "tulis_file"))  {

                if (inside_func  ==  1)  {

                    global_code  =  __wear_concat(global_code ,  "__wear_write_file");

                } else  {

                    main_code  =  __wear_concat(main_code ,  "__wear_write_file");

                }

                need_semi  =  1;

            } else if (__wear_streq(word,  "panjang"))  {

                if (inside_func  ==  1)  {

                    global_code  =  __wear_concat(global_code ,  "__wear_strlen");

                } else  {

                    main_code  =  __wear_concat(main_code ,  "__wear_strlen");

                }

                need_semi  =  1;

            } else if (__wear_streq(word,  "char_at"))  {

                if (inside_func  ==  1)  {

                    global_code  =  __wear_concat(global_code ,  "__wear_char_at");

                } else  {

                    main_code  =  __wear_concat(main_code ,  "__wear_char_at");

                }

                need_semi  =  1;

            } else if (__wear_streq(word,  "sama"))  {

                if (inside_func  ==  1)  {

                    global_code  =  __wear_concat(global_code ,  "__wear_streq");

                } else  {

                    main_code  =  __wear_concat(main_code ,  "__wear_streq");

                }

                need_semi  =  1;

            } else if (__wear_streq(word,  "is_quote"))  {

                if (inside_func  ==  1)  {

                    global_code  =  __wear_concat(global_code ,  "__wear_is_quote");

                } else  {

                    main_code  =  __wear_concat(main_code ,  "__wear_is_quote");

                }

                need_semi  =  1;

            } else if (__wear_streq(word,  "quote_char"))  {

                if (inside_func  ==  1)  {

                    global_code  =  __wear_concat(global_code ,  "__wear_quote_char");

                } else  {

                    main_code  =  __wear_concat(main_code ,  "__wear_quote_char");

                }

                need_semi  =  1;

            } else if (__wear_streq(word,  "is_newline"))  {

                if (inside_func  ==  1)  {

                    global_code  =  __wear_concat(global_code ,  "__wear_is_newline");

                } else  {

                    main_code  =  __wear_concat(main_code ,  "__wear_is_newline");

                }

                need_semi  =  1;

            } else if (__wear_streq(word,  "newline_char"))  {

                if (inside_func  ==  1)  {

                    global_code  =  __wear_concat(global_code ,  "__wear_newline_char");

                } else  {

                    main_code  =  __wear_concat(main_code ,  "__wear_newline_char");

                }

                need_semi  =  1;

            } else  {

                

                

                 int peek_idx = i;

                 int found_plus = 0;

                

                while (peek_idx  <  len)  {

                     char* peek_ch = __wear_char_at(source,  peek_idx);

                    if (is_space(peek_ch))  {

                        peek_idx  =  peek_idx  +  1;

                    } else if (__wear_streq(peek_ch,  "+"))  {

                        found_plus  =  1;

                        peek_idx  =  len;

                    } else  {

                        peek_idx  =  len;

                    }

                }

                

                

                if (found_plus  ==  1)  {

                    if (is_string_varname(word))  {

                        if (inside_func  ==  1)  {

                            global_code  =  __wear_concat(global_code ,  "__wear_concat(");

                            global_code  =  __wear_concat(global_code ,  word);

                        } else  {

                            main_code  =  __wear_concat(main_code ,  "__wear_concat(");

                            main_code  =  __wear_concat(main_code ,  word);

                        }

                        pending_concat  =  pending_concat  +  1;

                    } else  {

                        if (inside_func  ==  1)  {

                            global_code  =  __wear_concat(global_code ,  word);

                        } else  {

                            main_code  =  __wear_concat(main_code ,  word);

                        }

                    }

                } else  {

                    if (inside_func  ==  1)  {

                        global_code  =  __wear_concat(global_code ,  word);

                    } else  {

                        main_code  =  __wear_concat(main_code ,  word);

                    }

                }

                last_operand  =  word;

                need_semi  =  1;

            }

        } else  {

            i  =  i  +  1;

        }

    }

}





if (need_semi  ==  1)  {

    if (in_print  ==  1)  {

        main_code  =  __wear_concat(main_code ,  ");");

    } else  {

        main_code  =  __wear_concat(main_code ,  ";");

    }

}







 char* final_output = "";

final_output  =  __wear_concat(final_output ,  "/* Generated by WeaR Lang Self-Hosted Transpiler */");

final_output  =  __wear_concat(final_output ,  nl);

final_output  =  __wear_concat(final_output ,  nl);

final_output  =  __wear_concat(final_output ,  runtime_code);

final_output  =  __wear_concat(final_output ,  nl);

final_output  =  __wear_concat(final_output ,  nl);

final_output  =  __wear_concat(final_output ,  global_code);

final_output  =  __wear_concat(final_output ,  nl);

final_output  =  __wear_concat(final_output ,  "int main() {");

final_output  =  __wear_concat(final_output ,  nl);

final_output  =  __wear_concat(final_output ,  main_code);

final_output  =  __wear_concat(final_output ,  nl);

final_output  =  __wear_concat(final_output ,  "return 0;");

final_output  =  __wear_concat(final_output ,  nl);

final_output  =  __wear_concat(final_output ,  "}");





__wear_write_file("output.c",  final_output);



__wear_print_str("Generated: output.c");

__wear_print_str("Transpilation complete!");






return 0;
}